climatic_missing function documentation
IDEMSInternational/standAloneFunctionsR pull request #19
Opened 2023-06-29 08:59 UTC by EVANSTATS

Hey @lilyclements please review this.

2023-07-03 09:38 UTC, lilyclements requested changes

2023-07-03 09:38 UTC, lilyclements commented on R/climatic_missing.R
> +#' climatic_missing
@EVANSTATS can we have a more informative title here? If you're not sure of a better title, we can always leave it for now and ask Roger at a later date.
From reading the description, I would suggest something like "Summarise missing climatic values"?

2023-07-10 07:04 UTC, EVANSTATS commented
Hey @lilyclements I have made the changes.

2023-07-10 13:57 UTC, lilyclements approved these changes

2023-07-10 13:57 UTC, merged